### ISSUE TITLE
Update wiki pages in the main repo

### ISSUE THREAD

**Issue by jakubsuchybio** [PoGo-Devs/PoGo#2]
I updated wiki on my local fork to be merged in main repo with:
### **Home:**
- Updated section `Installation instructions` when someone encounters issues
- Updated section `Known issues` for users to check latest Release's Known Issues
- Updated section `How to help`
- Updated section `FAQ`
### **Dev:**
- Updated ApplicationKeys.cs info
- Updated FAQ

My forked commit here: 
https://github.com/jakubsuchybio/PoGo-UWP/wiki/Home/95f160ced4a2ced19c4238bef05a7e0bafa2b7fe

**Comment by Kaankehh** [comment]
It is not needed, this place is for developers only. We will still use the other repo.
