### ISSUE TITLE
Add new labels to the project.

### ISSUE THREAD

**Issue by robertmclaws** [PoGo-Devs/PoGo#32]
We need a "GameClients" and a "Backlog" label, por-favor.

**Comment by ST-Apps** [comment]
I'm quite sure that you can add them yourself.
If not, choose the colors and you'll have them asap!

**Comment by robertmclaws** [comment]
I don't get the "gear" tab to change project settings. Colors don't really matter to me either. Just looking for a way to categorize stuff :)

**Comment by ST-Apps** [comment]
You don't need to access that, go to Issues > Labels > New label and let me know if it worked :)

**Comment by robertmclaws** [comment]
Oh. Hi. There it is. Thanks. Not sure why they don't let you add new labels from the dropdown. But that worked. Structure I used is, dark colors are for decisions/discussion, light colors are for parts of the architecture.
