### ISSUE TITLE
can't find any gyms on maps,can't use rass berry,incense,layer module,etc plz help

### ISSUE THREAD

**Issue by ghost** [PoGo-Devs/PoGo#37]
## Device info
- Phone type: (e.g. Lumia 950 XL)
- App version: (e.g. 1.0.25)

**Comment by josecfreittas** [comment]
Wait for the implementation of these functions. [And look for old issues before creating new ones.](https://github.com/ST-Apps/PoGo-UWP/issues?utf8=✓&q=use%20items)
