### ISSUE TITLE
(Suggestion) Add contribution guidelines

### ISSUE THREAD

**Issue by ghost** [PoGo-Devs/PoGo#7]
My suggestion is to add a CONTRIBUTING.md

We would have to decide on preferred indentation style, line endings and whitespace.
I propose classic Allman style, LF line endings and 4 spaces.
This is pretty much default everywhere, but as long as we decide on common ground, it's fine.

The only exception is the XLF files, where CLRF must be enforced, because VS will mess the up otherwise.

**Comment by jakubsuchybio** [comment]
I agree, but better solution would be to have solution wide formatting enforcing via rebracer or there is one other extension that applies formatting from file in repo. (In the future VS they will have this option by default in vs, not now, dunno when) And we can also enforce it automatically by some code climate setting i think on every pr.

**Comment by ghost** [comment]
@jakubsuchybio Well better be idiot proof then sorry. VS extension might be good in closed projects, but there's always this one guy that won't use it.
If it can be enforced per PR then I'm all for it. Will it change the commits, or just not accept PRs that don't follow the guidelines?

**Comment by ST-Apps** [comment]
@spades789 I'm not really confident with those things, can you please create that file and add it to the repo?

**Comment by ghost** [comment]
Ok so we need to make sure we are on the same boat.
What indentation, what spaces, what line endings?

**Comment by ST-Apps** [comment]
I'm on for what you proposed in the OP.

**Comment by Seelengrab** [comment]
Since this is supposed to be compiled for a Windows Environment, wouldn't CRLF line endings make more sense since that's the Windows default? Would also stop VS from making a fuss.

**Comment by ST-Apps** [comment]
Ok, we already have `crlf` in `.gitattributes`, let's stick to that.

**Comment by ghost** [comment]
Better make a line ending pass on all files to exchange all LF with CRLF.
But be sure you are not replacing the LF in CRLF, then we would have CRCRLF :D

**Comment by Seelengrab** [comment]
Yes. should be done with everything coming in from the old repo, you never know. This will make a good baseline so we'll be able to tell from the commits and git blame who broke it.

**Comment by ghost** [comment]
So we came up with this base, if anyone wants to add/change/remove something, you can start here:
http://pastebin.com/VdMipRK4

**Comment by Seelengrab** [comment]
Some things still have to be added, for example "How to contact the developers" or "Getting started". There's also still some discussion about how to format commits (using imperative or not, for example).

**Comment by Chatfix** [comment]
#19

**Comment by jakubsuchybio** [comment]
Oh sorry didn't see this thread. To be honest I just copied and changed the [Powershell Contribution guidelines](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md). As they are OSS on github I didn't see a problem with that, because they use MIT Licence, which grants this.

However we should still have this open for changes, that are still not there. Like maybe some LINTing or formatting guides.

**Comment by Seelengrab** [comment]
But.. we agreed on how we'd do it and EVERYTHING D:
