### ISSUE TITLE
(Suggestion) Add trello board or something similar

### ISSUE THREAD

**Issue by ghost** [PoGo-Devs/PoGo#8]
Could we also add a Trello board, or some similar tool for splitting up the workforce?
It is really painfull to see your hard work thrown in trash, because someone already made the same thing, without you knowing.

With Trello we could set up goals, that people can say they are working on, showing their progress before even sending a PR.

**Comment by Kaankehh** [comment]
Sounds actually really handy.
It is indeed quite annoying to make something and then when you are about to make a PR you see your work has been comitted o.O

**Comment by ST-Apps** [comment]
I've never used Trello, isn't GitHub enough? People can be assigned to issues and you can have tasks inside issues/PRs.

**Comment by ghost** [comment]
@ST-Apps We'll have to see how it works out. But if there is known issue you want to fix, but the issue itself is not created, do you create a new issue just to assign it to yourself?
We do this with bugzilla, but I find it weird.

**Comment by jakubsuchybio** [comment]
I think github have a good backlog environment for this. If there is not a known issue created in github I would agree to create it by yourself and if you want to work on it, you could assign yourself. 

However if it doesn't work to our liking we can definitely try something else for sure. :)
